services:

  server-app:
    container_name: server-app
    build: ./server
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: $SERVER_SECRET_KEY
      DATABASE_URI: $SERVER_DATABASE_URI
    volumes:
      - ./server:/app
    env_file:
      - ./envs/server/.env
    depends_on:
      - postgres
      - redis

  client-app:
    container_name: client-app
    build: ./client
    depends_on:
      - server-app
    env_file:
      - ./envs/client/.env
    ports:
      - 80:80

  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./envs/db/.env

  redis:
    container_name: redis
    image: redis:7.2.1-alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - ./envs/redis/.env

  # redis-commander:
  #   container_name: redis-commander
  #   image: rediscommander/redis-commander:latest
  #   ports:
  #       - 8081:8081
  #   environment:
  #       - REDIS_HOSTS=$REDIS_COMMANDER_HOSTS
  #       - REDIS_PASSWORD=$REDIS_PASSWORD
  #   env_file:
  #     - ./envs/redis/.env
  #   depends_on:
  #       - redis

volumes:
  postgres_data:
