version: '3'
services:
  
  server-app:
    container_name: server-app
    build: ./server
    ports:
      - $SERVER_LOCAL_PORT:$SERVER_DOCKER_PORT
    environment:
      SECRET_KEY: $SERVER_SECRET_KEY
      DATABASE_URI: $SERVER_DATABASE_URI
    env_file:
      - .env
    depends_on:
      - postgres
    
  client-app:
    container_name: client-app
    build: ./client
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres:15  
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./temp/psqlDB:/var/lib/postgresql/data
    env_file:
      - .env

  # redis:
  #   container_name: redis
  #   image: redis:7.2.1-alpine
  #   ports:
  #     - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT
  #   environment:
  #     - REDIS_PASSWORD=$REDIS_PASSWORD
  #   env_file:
  #     - .env

  # redis-commander:
  #   container_name: redis-commander
  #   image: rediscommander/redis-commander:latest
  #   ports:
  #       - $REDIS_COMMANDER_LOCAL_PORT:$REDIS_COMMANDER_DOCKER_PORT
  #   environment:
  #       - REDIS_HOSTS=$REDIS_COMMANDER_HOSTS
  #       - REDIS_PASSWORD=$REDIS_PASSWORD
  #   env_file:
  #     - .env
  #   depends_on:
  #       - redis

  # adminer:
  #   container_name: adminer
  #   image: adminer:latest
  #   ports:
  #     - $ADMINER_LOCAL_PORT:$ADMINER_DOCKER_PORT
  #   env_file:
  #     - .env
  #   depends_on: 
  #     - postgres