version: '3'
services:
  
  server-app:
    container_name: server-app
    build: ./server
    ports:
      - 5000:5000
    environment:
      SECRET_KEY: $SERVER_SECRET_KEY
      DATABASE_URI: $SERVER_DATABASE_URI
    volumes:
      - ./server:/app
    env_file:
      - .env
    depends_on:
      - postgres
      # - mailhog

  client-app:
    container_name: client-app
    build: ./client
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres:15  
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_MULTIPLE_DATABASES: $POSTGRES_TEST_DB
    volumes:
      - ./db/temp/psqlDB:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/multiple-db.sh
    env_file:
      - .env

  # redis:
  #   container_name: redis
  #   image: redis:7.2.1-alpine
  #   ports:
  #     - 6379:6379
  #   environment:
  #     - REDIS_PASSWORD=$REDIS_PASSWORD
  #   env_file:
  #     - .env

  # redis-commander:
  #   container_name: redis-commander
  #   image: rediscommander/redis-commander:latest
  #   ports:
  #       - 8081:8081
  #   environment:
  #       - REDIS_HOSTS=$REDIS_COMMANDER_HOSTS
  #       - REDIS_PASSWORD=$REDIS_PASSWORD
  #   env_file:
  #     - .env
  #   depends_on:
  #       - redis

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8082:8080
    env_file:
      - .env
    depends_on:
      - postgres

  # mailhog:
  #   container_name: mailhog
  #   image: mailhog/mailhog
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
