services:

  server-app:
    container_name: server-app
    build: ./server
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/app

  client-app:
    container_name: client-app
    build: ./client
    ports:
      - 3000:3000
    tty: true
    env_file:
      - ./client/.env
    depends_on:
      - server-app
    volumes:
      - ./client:/app
      - /app/node_modules

  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - ./db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.2.1-alpine
    ports:
      - 6379:6379
    env_file:
      - ./redis/.env
    command: ["sh", "-c", "redis-server --requirepass \"$$REDIS_PASSWORD\""]

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8082:8080
    depends_on:
      - postgres

volumes:
  postgres_data: