services:

  server-app:
    container_name: server-app
    build: ./server
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/app

  client-app:
    container_name: client-app
    build: ./client
    ports:
      - 80:80
    env_file:
      - ./client/.env
    depends_on:
      - server-app

  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    env_file:
      - ./db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.2.1-alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    env_file:
      - ./redis/.env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  postgres_data: