export const FIELD_LABELS = {
	DISCOUNT: {
		discount_name: 'Название скидки',
		discount_type: 'Тип скидки',
		percentage_value: 'Процент скидки',
	},
	BOOKING: {
		booking_number: 'Номер бронирования',
		status: 'Статус',
		email_address: 'Электронная почта',
		phone_number: 'Телефон',
		first_name: 'Имя',
		last_name: 'Фамилия',
		currency: 'Валюта',
		base_price: 'Базовая цена',
		final_price: 'Итоговая цена',
	},
	AIRPORT: {
        name: 'Название аэропорта',
        iata_code: 'Код IATA',
        icao_code: 'Код ICAO',
        city_name: 'Город',
        city_name_en: 'Город (EN)',
        city_code: 'Код города',
        country_id: 'Страна',
    },
	FLIGHT: {
		flight_number: 'Номер рейса',
		route_id: 'Маршрут рейса',
		airline_id: 'Авиакомпания',
		origin_airport_id: 'Аэропорт отправления',
		destination_airport_id: 'Аэропорт прибытия',
		scheduled_departure: 'Время отправления',
		scheduled_arrival: 'Время прибытия',
		status: 'Статус рейса',
		tariffs: 'Тарифы',
	},
	PASSENGER: {
		first_name: 'Имя',
		last_name: 'Фамилия',
		middle_name: 'Отчество',
		gender: 'Пол',
		birth_date: 'Дата рождения',
		document_type: 'Тип документа',
		document_number: 'Номер документа',
	},
	TICKET: {
		ticket_number: 'Номер билета',
		booking_id: 'ID бронирования',
		passenger_id: 'ID пассажира',
		flight_id: 'ID рейса',
		seat_number: 'Номер места',
		seat_class: 'Класс места',
		price: 'Цена',
	},
	PAYMENT: {
		booking_id: 'ID бронирования',
		amount: 'Сумма',
		currency: 'Валюта',
		status: 'Статус платежа',
		method: 'Метод оплаты',
		transaction_id: 'ID транзакции',
		payment_date: 'Дата платежа',
	},
	AIRLINE: {
		iata_code: 'Код IATA',
		icao_code: 'Код ICAO',
		name: 'Название авиакомпании',
		country_id: 'Страна',
	},
	COUNTRY: {
		name: 'Название',
		name_en: 'Название (EN)',
		code_a2: 'Код A2',
		code_a3: 'Код A3',
	},
	ROUTE: {
		flight_number: 'Номер рейса',
		origin_airport_id: 'Аэропорт отправления',
		destination_airport_id: 'Аэропорт прибытия',
		departure_time: 'Время отправления',
		arrival_time: 'Время прибытия',
	},
	TARIFF: {
		name: 'Название тарифа',
		description: 'Описание',
		currency: 'Валюта',
		seats_number: 'Количество мест',
		price: 'Цена',
		seat_class: 'Класс места',
	},
	USER: {
		email: 'Электронная почта',
		password: 'Пароль',
		role: 'Роль пользователя',
		is_active: 'Активен',
	},
};

export default FIELD_LABELS;
