export const FIELD_LABELS = {
	DISCOUNT: {
		discount_name: 'Название скидки',
		discount_type: 'Тип скидки',
		percentage_value: 'Процент скидки',
	},
	FEE: {
		name: 'Наименование сбора',
		description: 'Описание',
		amount: 'Сумма',
		application: 'Применение сбора',
		application_term: 'Срок применения сбора',
	},
	BOOKING: {
		public_id: 'ID бронирования',
		booking_number: 'Номер бронирования',
		booking_date: 'Дата бронирования',
		status: 'Статус бронирования',
		buyer_last_name: 'Фамилия покупателя',
		buyer_first_name: 'Имя покупателя',
		email_address: 'Электронная почта',
		phone_number: 'Телефон',
		currency: 'Валюта',
		fare_price: 'Стоимость перевозки',
		total_discounts: 'Скидка',
		fees: 'Сборы',
		total_price: 'Итого',
		quantity: 'Кол-во',
		ticket_price: 'Цена билета',
		passengers: 'Пассажиры',
	},
	AIRPORT: {
		name: 'Название аэропорта',
		iata_code: 'Код IATA',
		icao_code: 'Код ICAO',
		city_name: 'Город',
		city_name_en: 'Город (EN)',
		city_code: 'Код города',
		country_id: 'Страна',
		timezone_id: 'Часовой пояс',
	},
	FLIGHT: {
		flight_number: 'Номер рейса',
		airline_id: 'Авиакомпания',
		aircraft_id: 'Воздушное судно',
		route_id: 'Маршрут рейса',
		origin_airport_id: 'Аэропорт отправления',
		destination_airport_id: 'Аэропорт прибытия',
		scheduled_departure: 'Дата отправления',
		scheduled_departure_time: 'Время отправления',
		scheduled_arrival: 'Дата прибытия',
		scheduled_arrival_time: 'Время прибытия',
		duration: 'Длительность полета',
		status: 'Статус рейса',
		note: 'Примечания',
		tariffs: 'Тарифы',
	},
	PASSENGER: {
		first_name: 'Имя',
		last_name: 'Фамилия',
		patronymic_name: 'Отчество',
		gender: 'Пол',
		birth_date: 'Дата рождения',
		document_type: 'Тип документа',
		document_number: 'Номер документа',
		document_expiry_date: 'Срок действия',
		citizenship_id: 'Гражданство',
		owner_user_id: 'Пользователь',
	},
	BOOKING_PASSENGER: {
		booking_id: 'Бронирование',
		passenger_id: 'Пассажир',
	},
	TICKET: {
		ticket_number: 'Номер билета',
		booking_id: 'ID бронирования',
		passenger_id: 'ID пассажира',
		flight_id: 'ID рейса',
		price: 'Цена',
	},
	PAYMENT: {
		booking_id: 'Бронирование',
		payment_method: 'Метод оплаты',
		payment_status: 'Статус платежа',
		payment_type: 'Тип платежа',
		amount: 'Сумма',
		currency: 'Валюта',
		expires_at: 'Истекает',
		paid_at: 'Дата оплаты',
		provider_payment_id: 'ID провайдера',
		confirmation_token: 'Токен подтверждения',
		is_paid: 'Оплачен',
	},
	AIRLINE: {
		iata_code: 'Код IATA',
		icao_code: 'Код ICAO',
		name: 'Название авиакомпании',
		country_id: 'Страна',
	},
	AIRCRAFT: {
		type: 'Тип воздушного судна',
	},
	COUNTRY: {
		name: 'Название',
		name_en: 'Название (EN)',
		code_a2: 'Код A2',
		code_a3: 'Код A3',
	},
	ROUTE: {
		origin_airport_id: 'Аэропорт отправления',
		destination_airport_id: 'Аэропорт прибытия',
		departure_time: 'Время отправления',
		arrival_time: 'Время прибытия',
	},
	TARIFF: {
		seat_class: 'Класс обслуживания',
		order_number: 'Номер тарифа',
		title: 'Наименование тарифа',
		price: 'Цена',
		currency: 'Валюта',
		conditions: 'Условия применения тарифа',
		baggage: 'Багаж (кг)',
		hand_luggage: 'Ручная кладь (кг)',
	},
	FLIGHT_TARIFF: {
		flight_id: 'Рейс',
		tariff_id: 'Тариф',
		seats_number: 'Количество мест',
	},
	USER: {
		email: 'Электронная почта',
		password: 'Пароль',
		role: 'Роль пользователя',
		is_active: 'Активен',
	},
	TIMEZONE: {
		name: 'Часовой пояс',
	},
	CONSENT_DOC: {
		type: 'Тип документа',
		version: 'Версия',
		content: 'Содержание',
	},
	CONSENT_EVENT: {
		type: 'Тип события',
		granter_user_id: 'Пользователь',
		booking_id: 'Бронирование',
		doc_id: 'Документ согласия',
		action: 'Действие',
		ip: 'IP адрес',
		user_agent: 'User-Agent',
		device_fingerprint: 'Отпечаток устройства',
		subject_ids: 'Субъекты согласия',
	},
};

export default FIELD_LABELS;
