export const FIELD_LABELS = {
	DISCOUNT: {
		discount_name: 'Название скидки',
		discount_type: 'Тип скидки',
		percentage_value: 'Процент скидки',
	},
	BOOKING: {
		booking_number: 'Номер бронирования',
		booking_date: 'Дата бронирования',
		status: 'Статус бронирования',
		email_address: 'Электронная почта',
		phone_number: 'Телефон',
		currency: 'Валюта',
		base_price: 'Базовая цена',
		final_price: 'Итоговая цена',
		passengers: 'Пассажиры',
	},
	AIRPORT: {
		name: 'Название аэропорта',
		iata_code: 'Код IATA',
		icao_code: 'Код ICAO',
		city_name: 'Город',
		city_name_en: 'Город (EN)',
		city_code: 'Код города',
		country_id: 'Страна',
		timezone_id: 'Часовой пояс',
	},
	FLIGHT: {
		flight_number: 'Номер рейса',
		airline_id: 'Авиакомпания',
		aircraft_id: 'Воздушное судно',
		route_id: 'Маршрут рейса',
		origin_airport_id: 'Аэропорт отправления',
		destination_airport_id: 'Аэропорт прибытия',
		scheduled_departure: 'Дата отправления',
		scheduled_departure_time: 'Время отправления',
		scheduled_arrival: 'Дата прибытия',
		scheduled_arrival_time: 'Время прибытия',
		duration: 'Длительность полета',
		status: 'Статус рейса',
		tariffs: 'Тарифы',
	},
	PASSENGER: {
		first_name: 'Имя',
		last_name: 'Фамилия',
		gender: 'Пол',
		birth_date: 'Дата рождения',
		document_type: 'Тип документа',
		document_number: 'Номер документа',
		document_expiry_date: 'Срок действия документа',
		citizenship_id: 'Гражданство',
	},
	BOOKING_PASSENGER: {
		booking_id: 'Бронирование',
		passenger_id: 'Пассажир',
		is_contact: 'Контактное лицо',
	},
	TICKET: {
		ticket_number: 'Номер билета',
		booking_id: 'ID бронирования',
		passenger_id: 'ID пассажира',
		flight_id: 'ID рейса',
		seat_number: 'Номер места',
		seat_class: 'Класс места',
		price: 'Цена',
	},
	PAYMENT: {
		booking_id: 'ID бронирования',
		amount: 'Сумма',
		currency: 'Валюта',
		status: 'Статус платежа',
		method: 'Метод оплаты',
		transaction_id: 'ID транзакции',
		payment_date: 'Дата платежа',
	},
	AIRLINE: {
		iata_code: 'Код IATA',
		icao_code: 'Код ICAO',
		name: 'Название авиакомпании',
		country_id: 'Страна',
	},
	AIRCRAFT: {
		type: 'Тип воздушного судна',
	},
	COUNTRY: {
		name: 'Название',
		name_en: 'Название (EN)',
		code_a2: 'Код A2',
		code_a3: 'Код A3',
	},
	ROUTE: {
		origin_airport_id: 'Аэропорт отправления',
		destination_airport_id: 'Аэропорт прибытия',
		departure_time: 'Время отправления',
		arrival_time: 'Время прибытия',
	},
	TARIFF: {
		seat_class: 'Класс обслуживания',
		order_number: 'Наименование тарифа',
		price: 'Цена',
		currency: 'Валюта',
		conditions: 'Условия применения тарифа',
	},
	FLIGHT_TARIFF: {
		flight_id: 'Рейс',
		tariff_id: 'Тариф',
		seats_number: 'Количество мест',
	},
	USER: {
		email: 'Электронная почта',
		password: 'Пароль',
		role: 'Роль пользователя',
		is_active: 'Активен',
	},
	TIMEZONE: {
		name: 'Часовой пояс',
	},
};

export default FIELD_LABELS;
