"""Airline and airport internal codes

Revision ID: 02923ea4bc9e
Revises: ef7dd5015692
Create Date: 2025-11-02 14:01:18.766701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02923ea4bc9e'
down_revision = 'ef7dd5015692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_code', sa.String(length=2), nullable=True))

    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_code', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.drop_column('internal_code')

    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.drop_column('internal_code')

    # ### end Alembic commands ###
