"""Unique route

Revision ID: 0ade5bdb146c
Revises: b9e7f4fb42a8
Create Date: 2025-07-31 20:13:56.503799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ade5bdb146c'
down_revision = 'b9e7f4fb42a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_origin_destination_airport', ['origin_airport_id', 'destination_airport_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_constraint('uix_origin_destination_airport', type_='unique')

    # ### end Alembic commands ###
