"""Airplane seats number

Revision ID: 12158a6f653d
Revises: 9675bd2222b2
Create Date: 2025-10-29 19:36:22.327318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12158a6f653d'
down_revision = '9675bd2222b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircrafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('economy_seats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('business_seats', sa.Integer(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE aircrafts SET economy_seats = 0 WHERE economy_seats IS NULL")
    op.execute("UPDATE aircrafts SET business_seats = 0 WHERE business_seats IS NULL")
    
    # Make columns non-nullable
    with op.batch_alter_table('aircrafts', schema=None) as batch_op:
        batch_op.alter_column('economy_seats', nullable=False)
        batch_op.alter_column('business_seats', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircrafts', schema=None) as batch_op:
        batch_op.drop_column('business_seats')
        batch_op.drop_column('economy_seats')

    # ### end Alembic commands ###
