"""Ticket model refactored

Revision ID: 16289848709a
Revises: 9e90d90845f0
Create Date: 2025-11-09 10:59:51.354695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16289848709a'
down_revision = '9e90d90845f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Create the new booking_flight_passengers table
    op.create_table('booking_flight_passengers',
                    sa.Column('booking_passenger_id',
                              sa.Integer(), nullable=False),
                    sa.Column('flight_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('created', 'ticket_in_progress', 'ticketed',
                                                name='booking_flight_passenger_status'), nullable=False),
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['booking_passenger_id'], [
                        'booking_passengers.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['flight_id'], ['flights.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('booking_passenger_id', 'flight_id',
                                        name='uix_booking_flight_passenger_unique')
                    )

    # Step 2: Clear all tickets
    op.execute('DELETE FROM tickets')

    # Step 3: Populate booking_flight_passengers for all existing bookings
    # Get all booking_passenger_id and flight_id combinations from bookings
    connection = op.get_bind()

    # Get all booking passengers
    booking_passengers = connection.execute(sa.text(
        'SELECT id, booking_id FROM booking_passengers'
    )).fetchall()

    # Get all flights for each booking
    from datetime import datetime
    now = datetime.now()

    for bp_row in booking_passengers:
        bp_id = bp_row[0]
        booking_id = bp_row[1]

        # Get all flight_ids for this booking through booking_flights -> flight_tariffs -> flights
        flight_ids = connection.execute(sa.text('''
            SELECT DISTINCT ft.flight_id
            FROM booking_flights bf
            JOIN flight_tariffs ft ON bf.flight_tariff_id = ft.id
            WHERE bf.booking_id = :booking_id AND ft.flight_id IS NOT NULL
        '''), {'booking_id': booking_id}).fetchall()

        # Create a booking_flight_passenger entry for each passenger/flight combination
        for flight_row in flight_ids:
            flight_id = flight_row[0]
            connection.execute(sa.text('''
                INSERT INTO booking_flight_passengers 
                (booking_passenger_id, flight_id, status, created_at, updated_at)
                VALUES (:bp_id, :flight_id, 'created', :now, :now)
                ON CONFLICT DO NOTHING
            '''), {'bp_id': bp_id, 'flight_id': flight_id, 'now': now})

    # Step 4: Modify the tickets table
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('booking_flight_passenger_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f(
            'tickets_booking_passenger_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f(
            'tickets_flight_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'booking_flight_passengers', [
                                    'booking_flight_passenger_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('flight_id')
        batch_op.drop_column('booking_passenger_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_passenger_id',
                            sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(
            sa.Column('flight_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tickets_flight_id_fkey'), 'flights', [
                                    'flight_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('tickets_booking_passenger_id_fkey'), 'booking_passengers', [
                                    'booking_passenger_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('booking_flight_passenger_id')

    op.drop_table('booking_flight_passengers')
    # ### end Alembic commands ###
