"""Flight notes, tariff title, uix Flight Tariff

Revision ID: 23abb78a7bf5
Revises: aaa7784d9186
Create Date: 2025-08-06 13:04:23.175961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23abb78a7bf5'
down_revision = 'aaa7784d9186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_tariffs', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_flight_tariff_flight_tariff', [
                                          'flight_id', 'tariff_id'])

    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(), nullable=True))

    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(),
                            nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('flight_tariffs', schema=None) as batch_op:
        batch_op.drop_constraint(
            'uix_flight_tariff_flight_tariff', type_='unique')

    # ### end Alembic commands ###
