"""Ticket model modified

Revision ID: 3758239e9a5b
Revises: 02923ea4bc9e
Create Date: 2025-11-03 08:52:53.976045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3758239e9a5b'
down_revision = '02923ea4bc9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_passenger_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('tickets_passenger_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tickets_discount_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tickets_booking_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'booking_passengers', ['booking_passenger_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('passenger_id')
        batch_op.drop_column('booking_id')
        batch_op.drop_column('discount_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('passenger_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tickets_booking_id_fkey'), 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('tickets_discount_id_fkey'), 'discounts', ['discount_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('tickets_passenger_id_fkey'), 'passengers', ['passenger_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('booking_passenger_id')

    # ### end Alembic commands ###
