"""Passenger snapshot

Revision ID: 386f74570467
Revises: 1df61dd5d684
Create Date: 2025-12-03 20:27:38.186415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '386f74570467'
down_revision = '1df61dd5d684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_passengers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passenger_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('booking_passengers', schema=None) as batch_op:
        batch_op.drop_column('passenger_snapshot')

    # ### end Alembic commands ###
