"""empty message

Revision ID: 47d319fc4b84
Revises: 92f766c3162d
Create Date: 2025-08-20 12:58:37.992409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d319fc4b84'
down_revision = '92f766c3162d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.UUID(), nullable=True))
        batch_op.create_unique_constraint(None, ['access_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
