"""Refund request dates

Revision ID: 4bf53485439b
Revises: 5c4d955d228d
Create Date: 2025-11-16 12:51:23.293759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf53485439b'
down_revision = '5c4d955d228d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_flight_passengers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refund_request_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('refund_decision_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('refund_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_flight_passengers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refund_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('refund_decision_at')
        batch_op.drop_column('refund_request_at')

    # ### end Alembic commands ###
