"""New fields

Revision ID: 58b1af852ad7
Revises: 34fb1f4f1fa5
Create Date: 2025-07-02 10:41:19.418577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b1af852ad7'
down_revision = '34fb1f4f1fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('seats_tariff_id_seat_number_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['flight_id', 'seat_number'])
        batch_op.create_foreign_key(None, 'flights', ['flight_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('seats_tariff_id_seat_number_key'), ['tariff_id', 'seat_number'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('flight_id')

    # ### end Alembic commands ###
