"""empty message

Revision ID: 597b3b6cd53c
Revises: f741bdaedcbb
Create Date: 2025-08-11 10:51:19.723429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '597b3b6cd53c'
down_revision = 'f741bdaedcbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_passengers', schema=None) as batch_op:
        batch_op.drop_column('is_contact')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('created', 'pending_payment', 'confirmed', 'cancelled', name='booking_status'), server_default=sa.text("'created'::booking_status"), autoincrement=False, nullable=False))

    with op.batch_alter_table('booking_passengers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_contact', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
