"""Ticket refund

Revision ID: 5c4d955d228d
Revises: b12ba38b4b5d
Create Date: 2025-11-13 11:47:04.560169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4d955d228d'
down_revision = 'b12ba38b4b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_fees',
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('fee_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fee_id'], ['fees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_id', 'fee_id', name='uix_tariff_fee')
    )
    with op.batch_alter_table('booking_flight_passengers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refund_date', sa.Date(), nullable=True))

    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        # Add column as nullable first
        batch_op.add_column(sa.Column('ticket_return_allowed', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE tariffs SET ticket_return_allowed = false WHERE ticket_return_allowed IS NULL")
    
    # Now make the column NOT NULL
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.alter_column('ticket_return_allowed', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_column('ticket_return_allowed')

    with op.batch_alter_table('booking_flight_passengers', schema=None) as batch_op:
        batch_op.drop_column('refund_date')

    op.drop_table('tariff_fees')
    # ### end Alembic commands ###
