"""Flight tariff decomposition

Revision ID: 69042aa1fc1a
Revises: 7f1e3687d960
Create Date: 2025-07-20 12:45:23.796819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69042aa1fc1a'
down_revision = '7f1e3687d960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_tariffs',
                    sa.Column('flight_id', sa.Integer(), nullable=False),
                    sa.Column('tariff_id', sa.Integer(), nullable=False),
                    sa.Column('seats_number', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['flight_id'], ['flights.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['tariff_id'], ['tariffs.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('tariff_discount')
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'seats_tariff_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'flight_tariffs', ['tariff_id'], [
                                    'id'], ondelete='RESTRICT')

    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('order_number', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f(
            'tariffs_flight_id_fkey'), type_='foreignkey')
        batch_op.drop_column('flight_id')
        batch_op.drop_column('seats_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('seats_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(
            sa.Column('flight_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('tariffs_flight_id_fkey'), 'flights', [
                                    'flight_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('order_number')

    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('seats_tariff_id_fkey'), 'tariffs', [
                                    'tariff_id'], ['id'], ondelete='RESTRICT')

    op.create_table('tariff_discount',
                    sa.Column('tariff_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('discount_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], name=op.f(
                        'tariff_discount_discount_id_fkey'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], name=op.f(
                        'tariff_discount_tariff_id_fkey'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint(
                        'tariff_id', 'discount_id', name=op.f('tariff_discount_pkey'))
                    )
    op.drop_table('flight_tariffs')
    # ### end Alembic commands ###
