"""Flight status removed

Revision ID: 7f1e3687d960
Revises: de79608a883e
Create Date: 2025-07-19 09:34:53.379383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f1e3687d960'
down_revision = 'de79608a883e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('scheduled', 'delayed', 'departed', 'arrived', 'cancelled', name='flight_status'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
