"""empty message

Revision ID: 81886dc8747e
Revises: 47d319fc4b84
Create Date: 2025-08-21 09:20:38.793787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81886dc8747e'
down_revision = '47d319fc4b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_docs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('offer', 'pd_policy', name='consent_doc_type'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'version', name='uix_consent_doc_type_version')
    )
    op.create_table('consent_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('offer_acceptance', 'pd_processing', name='consent_event_type'), nullable=False),
    sa.Column('granter_user_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('agree', 'withdraw', name='consent_action'), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['consent_docs.id'], ),
    sa.ForeignKeyConstraint(['granter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_event_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('consent_event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consent_event_id'], ['consent_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['passengers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consent_event_id', 'subject_id', name='uix_consent_event_subject')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consent_event_subjects')
    op.drop_table('consent_events')
    op.drop_table('consent_docs')
    # ### end Alembic commands ###
