"""Passengers count

Revision ID: 8bd4f233fb0e
Revises: 4f7dbc0edcd8
Create Date: 2025-08-09 16:11:35.758694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8bd4f233fb0e'
down_revision = '4f7dbc0edcd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passenger_counts', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('passenger_counts')

    # ### end Alembic commands ###
