"""Tariff conditions

Revision ID: 8d5bd40f1ccb
Revises: 5bf1ba315812
Create Date: 2025-07-26 08:44:48.847620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5bd40f1ccb'
down_revision = '5bf1ba315812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conditions', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_column('conditions')

    # ### end Alembic commands ###
