"""Flight date and aircraft

Revision ID: 915a40b5fbae
Revises: 69042aa1fc1a
Create Date: 2025-07-20 17:35:17.407148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '915a40b5fbae'
down_revision = '69042aa1fc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aircraft', sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column('scheduled_departure_time', sa.Time(), nullable=True))
        batch_op.add_column(
            sa.Column('scheduled_arrival_time', sa.Time(), nullable=True))
        batch_op.alter_column('scheduled_departure',
                              existing_type=postgresql.TIMESTAMP(),
                              type_=sa.Date(),
                              nullable=False)
        batch_op.alter_column('scheduled_arrival',
                              existing_type=postgresql.TIMESTAMP(),
                              type_=sa.Date(),
                              nullable=False)
        batch_op.create_unique_constraint('uix_flight_number_airline_route_departure', [
                                          'flight_number', 'airline_id', 'route_id', 'scheduled_departure'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_constraint(
            'uix_flight_number_airline_route_departure', type_='unique')
        batch_op.alter_column('scheduled_arrival',
                              existing_type=sa.Date(),
                              type_=postgresql.TIMESTAMP(),
                              nullable=True)
        batch_op.alter_column('scheduled_departure',
                              existing_type=sa.Date(),
                              type_=postgresql.TIMESTAMP(),
                              nullable=True)
        batch_op.drop_column('scheduled_arrival_time')
        batch_op.drop_column('scheduled_departure_time')
        batch_op.drop_column('aircraft')

    # ### end Alembic commands ###
