"""empty message

Revision ID: 9a3ba2c66ebc
Revises: 06bfaade332a
Create Date: 2025-08-11 19:42:40.550703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3ba2c66ebc'
down_revision = '06bfaade332a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tariff_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tariffs', ['tariff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tariff_id')

    # ### end Alembic commands ###
