"""empty message

Revision ID: 9ae584e79586
Revises: 12881a7a7857
Create Date: 2025-08-24 16:54:42.635837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '9ae584e79586'
down_revision = '12881a7a7857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False, server_default='false'))

    op.execute(text("UPDATE users SET failed_login_attempts = 0, is_locked = false"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_locked')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
