"""Itinerary receipt path booking

Revision ID: 9e90d90845f0
Revises: 3758239e9a5b
Create Date: 2025-11-03 15:24:19.941383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e90d90845f0'
down_revision = '3758239e9a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itinerary_receipt_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('itinerary_receipt_path')

    # ### end Alembic commands ###
