"""Itinerary path moved

Revision ID: a418fd3e9b81
Revises: 16289848709a
Create Date: 2025-11-09 20:54:02.172975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a418fd3e9b81'
down_revision = '16289848709a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itinerary_receipt_path', sa.String(), nullable=True))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('itinerary_receipt_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itinerary_receipt_path', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('booking_flights', schema=None) as batch_op:
        batch_op.drop_column('itinerary_receipt_path')

    # ### end Alembic commands ###
