"""Aircraft table created

Revision ID: aaa7784d9186
Revises: 0ade5bdb146c
Create Date: 2025-08-05 09:19:24.937456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa7784d9186'
down_revision = '0ade5bdb146c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircrafts',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aircraft_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'aircrafts', ['aircraft_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('aircraft')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aircraft', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('aircraft_id')

    op.drop_table('aircrafts')
    # ### end Alembic commands ###
