"""Ticket unique for booking-flight-passenger

Revision ID: b12ba38b4b5d
Revises: a418fd3e9b81
Create Date: 2025-11-10 16:49:46.598116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12ba38b4b5d'
down_revision = 'a418fd3e9b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['booking_flight_passenger_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
