"""Timezone table and airport link

Revision ID: b9e7f4fb42a8
Revises: 8d5bd40f1ccb
Create Date: 2025-07-31 07:20:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b9e7f4fb42a8'
down_revision = '8d5bd40f1ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'timezones',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'timezones', ['timezone_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('timezone_id')

    op.drop_table('timezones')
    # ### end Alembic commands ###
