"""Patronymic name

Revision ID: d74379cff39c
Revises: 4a18cff59faa
Create Date: 2025-08-08 16:43:30.935692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74379cff39c'
down_revision = '4a18cff59faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patronymic_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.drop_column('patronymic_name')

    # ### end Alembic commands ###
