"""booking public id and passenger owner

Revision ID: e0e6509e0e21
Revises: d74379cff39c
Create Date: 2025-08-09 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0e6509e0e21'
down_revision = 'd74379cff39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False))
        batch_op.alter_column('base_price', new_column_name='fare_price')
        batch_op.alter_column('final_price', new_column_name='total_price')
        batch_op.add_column(sa.Column('total_discounts', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('fees', sa.Float(), nullable=False, server_default='0'))
    op.create_index('ix_bookings_public_id', 'bookings', ['public_id'], unique=True)

    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uix_passenger_unique', type_='unique')
    op.create_index('ix_passengers_owner_user_id', 'passengers', ['owner_user_id'], unique=False)
    op.create_foreign_key('fk_passengers_owner_user_id_users', 'passengers', 'users', ['owner_user_id'], ['id'])
    op.create_index(
        'ux_passenger_by_owner',
        'passengers',
        ['owner_user_id', 'first_name', 'last_name', 'birth_date', 'document_type', 'document_number'],
        unique=True,
        postgresql_where=sa.text('owner_user_id IS NOT NULL')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_passenger_by_owner', table_name='passengers')
    op.drop_constraint('fk_passengers_owner_user_id_users', 'passengers', type_='foreignkey')
    op.drop_index('ix_passengers_owner_user_id', table_name='passengers')
    with op.batch_alter_table('passengers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_passenger_unique', ['first_name', 'last_name', 'birth_date', 'document_type', 'document_number'])
        batch_op.drop_column('owner_user_id')

    op.drop_index('ix_bookings_public_id', table_name='bookings')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('fees')
        batch_op.drop_column('total_discounts')
        batch_op.alter_column('total_price', new_column_name='final_price')
        batch_op.alter_column('fare_price', new_column_name='base_price')
        batch_op.drop_column('public_id')
    # ### end Alembic commands ###
