"""Flight number is not unique

Revision ID: f0241f8cedfc
Revises: 915a40b5fbae
Create Date: 2025-07-22 05:51:33.966451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0241f8cedfc'
down_revision = '915a40b5fbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('flights_flight_number_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('flights_flight_number_key'), ['flight_number'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
